---
title: "O9 - Matrix I"
output: html_notebook
---

[Matrix](http://www.r-exercises.com/2015/11/28/matrix-exercises/)

01: 
```{r}
x <- 1:3
y <- 4:6
z <- 7:9
A <- matrix(c(x, y, z), nrow = 3, ncol = 3, dimnames = list(c('a', 'b', 'c')))
A
matrix(c(x, y, z), nrow = 3, ncol = 3, dimnames = list(c('a', 'b', 'c')), byrow = T)
#solution:
A1 <- cbind(x,y,z)
rownames(A) <- c('a', 'b', 'c')
A1
```


02:
```{r}
is.matrix(A)
```


03:
```{r}
v <- 1:12
B <- matrix(v, nrow = 4, dimnames = list(c('a', 'b', 'c', 'd'), c('x', 'y', 'z')))
B
matrix(v, nrow = 4, dimnames = list(c('a', 'b', 'c', 'd'), c('x', 'y', 'z')), byrow = T)
```


04:
```{r}
tB <- t(B)
tB
```


05: element wise multiplication
```{r}
tB * tB
```

06:
```{r}
A %*% tB
```


07:
```{r}
A %*% A
as.matrix(data.frame(A)) %*% as.matrix(data.frame(A))
```


08:
```{r}
B
subB <- B[c(2:4),]
subB
```


09: No. Incompatible dimensions
```{r}
A
B
3 * A
A + subB
A - subB
A + B
```


10:
```{r}
A1 <- matrix(runif(9), nrow = 3)
A1
A2 <- matrix(runif(12), nrow = 3)
A2
solve(A1, A2)
```

