---
title: "10 - Matrix II"
output: html_notebook
---

[Matrix](http://www.r-exercises.com/2016/12/08/matrix-vol-2-exercises/)

01: 
  A  B
a 1  6
b 2  7
c 3  8
d 4  9
e 5 10
```{r}
M <- matrix(c(1:10), nrow = 5, ncol = 2, dimnames = list(c('a', 'b', 'c', 'd', 'e'), c('A', 'B')))
M
```


02:
a. M[1,] # 1 6
b. M[,1] 
    1
    2
    3
    4
    5
c. M[3,2] # 8
d. M['e', 'A'] # 5
```{r}
M[1,]
M[,1]
M[3,2]
M['e', 'A']
```


03: 1 5 9
```{r}
N <- matrix(c(1:9), nrow = 3, ncol = 3, dimnames = list(c('a','b','c'),c('A','B','C')))
diag(N)
```


04:
```{r}
d <- diag(4, 3, 3)
d
is.matrix(d)
```


05:
a. rownames(M) # a b c
b. colnames(M) # d e f
```{r}
M <- matrix(c(1:9),3,3,byrow=T, dimnames=list(c('a','b','c'), c('d','e','f')))
rownames(M)
colnames(M)
```


06:
a. upper.tri(M)        #
F T T
F F T
F F F
b. lower.tri(M)        #
F F F
T F F
T T F
c. lower.tri(M,diag=T) #
T F F
T T F
T T T
```{r}
upper.tri(M)
lower.tri(M)
lower.tri(M, diag = T)
```


07:
1 2 3   1 4 7
4 5 6 * 2 5 8
7 8 9   3 6 9

1   8 21
8  25 48
21 48 81
```{r}
M=matrix(c(1:9),3,3,byrow=T)
N=matrix(c(1:9),3,3)
M*N
```


08:
1 2 3 %*% 1 4 7
4 5 6 %*% 2 5 8
7 8 9 %*% 3 6 9

11  32  50
32  77 122
50 122 194
```{r}
M=matrix(c(1:9),3,3,byrow=T)
N=matrix(c(1:9),3,3)
M%*%N
```


09:
  4  36 100
 36 100 196
100 196 324
```{r}
(M+N)^2
```


10:
1.0  0.5  0.4
2.0  1.0  0.7
2.3  1.3  1.0
```{r}
M/N
```

